using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Meziantou.Polyfill;

[StructLayout(LayoutKind.Auto)]
internal partial struct Members
{
    private static bool IncludeMember(IncludeContext context, string memberDocumentationId)
    {
        if (context.Options is not null && !context.Options.Include(memberDocumentationId))
            return false;

        var symbols = DocumentationCommentId.GetSymbolsForDeclarationId(memberDocumentationId, context.Compilation);
        IAssemblySymbol? accessibleFromAssembly = null;
        foreach (var symbol in symbols)
        {
            if (ReferenceEquals(symbol.ContainingAssembly, context.Compilation.Assembly))
                return false;

            // IsEmbeddedSymbol is a workaround for https://github.com/dotnet/roslyn/issues/79498
            if (context.Compilation.IsSymbolAccessibleWithin(symbol, context.Compilation.Assembly) && !IsEmbeddedSymbol(symbol))
            {
                if (accessibleFromAssembly is null)
                {
                    accessibleFromAssembly = symbol.ContainingAssembly;
                }
                else if (!ReferenceEquals(accessibleFromAssembly, symbol.ContainingAssembly))
                {
                    // The symbol is accessible from multiple assemblies, which would cause
                    // ambiguity (e.g. CS0433). Generate a local copy so the compiler prefers
                    // the current assembly's definition.
                    return true;
                }
            }
        }

        if (accessibleFromAssembly is not null)
            return false;

        return true;
    }

    private static bool SupportsStringToReadOnlySpanCharConversion(Compilation compilation)
    {
        var stringType = compilation.GetSpecialType(SpecialType.System_String);
        var charType = compilation.GetSpecialType(SpecialType.System_Char);
        var readOnlySpanType = compilation.GetTypeByMetadataName("System.ReadOnlySpan`1");
        if (readOnlySpanType is null)
            return false;

        var readOnlySpanOfChar = readOnlySpanType.Construct(charType);
        foreach (var member in stringType.GetMembers(WellKnownMemberNames.ImplicitConversionName).OfType<IMethodSymbol>())
        {
            if (member.MethodKind == MethodKind.Conversion &&
                member.Parameters.Length == 1 &&
                SymbolEqualityComparer.Default.Equals(member.Parameters[0].Type, stringType) &&
                SymbolEqualityComparer.Default.Equals(member.ReturnType, readOnlySpanOfChar))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsEmbeddedSymbol(ISymbol symbol)
    {
        if (symbol is not ITypeSymbol)
        {
            symbol = symbol.ContainingType;
        }

        if (symbol is not ITypeSymbol)
            return false;

        var attributeSymbol = symbol.ContainingAssembly.GetTypeByMetadataName("Microsoft.CodeAnalysis.EmbeddedAttribute");
        if (attributeSymbol is null)
            return false;

        var attributes = symbol.GetAttributes();
        foreach (var attribute in attributes)
        {
            if (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, attributeSymbol))
                return true;
        }

        return false;
    }

    private void AddSource(SourceProductionContext context, string path, string content)
    {
        context.AddSource(path, SourceText.From("// <auto-generated/>\n" + _extraDefines + content, Encoding.UTF8));
    }

    private readonly struct IncludeContext(Compilation compilation, PolyfillOptions? options)
    {
        public Compilation Compilation { get; } = compilation;
        public PolyfillOptions? Options { get; } = options;
    }
}
